version: '3'
volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups    
    ports:
      - "5432:5432"
  # celery:
  #   build: .
  #   command: "celery -A iot.celery worker --loglevel=info"
  #   volumes:
  #     - ./app/:/app
  #   env_file:
  #     - ./env/web-var.env
  #   depends_on:
  #     - redis
  #     - web
  web:
    build: .
    command: flask run --host=0.0.0.0
    env_file:
      - ./env/web-var.env
    volumes:
      - ./app/:/app
    ports:
      - "8000:5000"
    depends_on:
      - db